name: purple_starter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # System
  path_provider: ^2.0.0
  path: ^1.8.0

  # Data transformations
  pure: ^0.1.1
  fast_immutable_collections: ^7.0.0
  stream_transform: ^2.0.0

  # BLoC
  stream_bloc: ^0.3.0
  flutter_bloc: ^8.0.1

  # Code generation
  freezed_annotation: ^1.1.0

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter 

  # Logging
  l: ^3.1.0
  sentry_flutter: ^6.2.2

  # Persistance
  drift: ^1.2.0
  sqlite3_flutter_libs: ^0.5.0
  shared_preferences: ^2.0.13

  # HTTP
  dio: ^4.0.4
  retrofit: ^3.0.1

  # Navigation
  go_router: ^3.0.1

  # Utils
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.2.0
  build_runner: ^2.1.7
  freezed: ^1.1.0
  
flutter:
  uses-material-design: true
  generate: true
